### ISSUE TITLE
&nbsp;   in title tags 

### ISSUE THREAD

**Issue by kiuuik** [chriskrycho/evernote2md#1]
Thanks for sharing. In case you are still interested in this software I think I found an error. It's no problem if you don't answer - I understand that it was just an afternoon project and I could probably look at alternatives ...

I tried with ubutun 18.04 and installed rust/cargo (version 1.28.0) via `curl https://sh.rustup.rs -sSf | sh`(as explained at https://www.rust-lang.org/en-US/install.html). I didnt have a version from the ubuntu repo.

I think evernote2md can't handle `&nbsp;` inside title tags(<title></title>). After I remove these it seems to work.

It runs for some time. Then I get this kind of error. The line is  so long because I used the webclipper to save a long-form article.

    thread 'main' panicked at 'wat: Error { pos: 1004568:6026, kind: Syntax("Unexpected entity: nbsp") }', libcore/result.rs:945:5
    note: Run with `RUST_BACKTRACE=1` for a backtrace.

So I ran this 

    $ RUST_BACKTRACE=1 evernote2md Evernote.enex .
    thread 'main' panicked at 'wat: Error { pos: 1004568:6026, kind: Syntax("Unexpected entity: nbsp") }', libcore/result.rs:945:5
    stack backtrace:
    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
                at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
    1: std::sys_common::backtrace::print
                at libstd/sys_common/backtrace.rs:71
                at libstd/sys_common/backtrace.rs:59
    2: std::panicking::default_hook::{{closure}}
                at libstd/panicking.rs:211
    3: std::panicking::default_hook
                at libstd/panicking.rs:227
    4: std::panicking::rust_panic_with_hook
                at libstd/panicking.rs:511
    5: std::panicking::continue_panic_fmt
                at libstd/panicking.rs:426
    6: rust_begin_unwind
                at libstd/panicking.rs:337
    7: core::panicking::panic_fmt
                at libcore/panicking.rs:92
    8: core::result::unwrap_failed
    9: evernote2md::main
    10: std::rt::lang_start::{{closure}}
    11: std::panicking::try::do_call
                at libstd/rt.rs:59
                at libstd/panicking.rs:310
    12: __rust_maybe_catch_panic
                at libpanic_unwind/lib.rs:105
    13: std::rt::lang_start_internal
                at libstd/panicking.rs:289
                at libstd/panic.rs:392
                at libstd/rt.rs:58
    14: main
    15: __libc_start_main
    16: _start

**Comment by chriskrycho** [comment]
Huh. Interesting catch! You might open an issue upstream on serde-xml-rs – I *think* that'd be where the problem is!
